### ISSUE TITLE
请问有没有一种方法允许用户自定义词典位置和查询方法啊？

### ISSUE THREAD

**Issue by suliveevil** [ginqi7/dictionary-overlay#13]
我现在用的词典和猫大的不一样，如果能允许自定义词典位置和字段查询就好了。

```python
sdcv_dictionary_path = os.path.join(
    os.path.dirname(__file__), "resources", "kdic-ec-11w"
)
sdcv_dictionary = Dictionary(sdcv_dictionary_path, in_memory=True)

sdcv_words = {}
candidates = []
for word in sdcv_dictionary.keys():
    first_line_translation = sdcv_dictionary.dict[word].split()[0]
    candidate_word = word.lower().replace('"', " ")
    candidate_translation = first_line_translation.split(".")[-1].split(";")[0]

    sdcv_words[candidate_word] = candidate_translation
```

**Comment by suliveevil** [comment]
猫大的词典查询是

```python
first_line_translation = sdcv_dictionary.dict[word].split()[0]
```

我加载的 ECDICT 词典查询是

```python
first_line_translation = sdcv_dictionary.dict[word].split()[3]
```

**Comment by manateelazycat** [comment]
> 猫大的词典查询是
> 
> ```python
> first_line_translation = sdcv_dictionary.dict[word].split()[0]
> ```
> 
> 我加载的 ECDICT 词典查询是
> 
> ```python
> first_line_translation = sdcv_dictionary.dict[word].split()[3]
> ```

可以考虑用正则表达式提取一下， 这样就可以兼容各种sdcv词典

**Comment by suliveevil** [comment]
🤣 我现在属于是哪儿哪儿都不明白，要学的东西太多了。
争取尽快多学一点，把 Emacs 武装起来 😬

**Comment by qingshuizheng** [comment]
其实我想弄个纯音标的，特别想抓取 M-W online 的美式音标。不过现在就是想想，先跟着大佬开发一阵子再说。

**Comment by arstum** [comment]
> 其实我想弄个纯音标的，特别想抓取 M-W online 的美式音标。不过现在就是想想，先跟着大佬开发一阵子再说。

对于生词来说，音标确实很重要。

**Comment by qingshuizheng** [comment]
> > 其实我想弄个纯音标的，特别想抓取 M-W online 的美式音标。不过现在就是想想，先跟着大佬开发一阵子再说。
> 
> 对于生词来说，音标确实很重要。

最近太忙，都没怎么折腾 d-o，有空再搞

**Comment by ginqi7** [comment]
通过变量 `dictionary-overlay-sdcv-dictionary-path` 支持自定义StarDict 词典

默认值 nil, 此时会使用 dictionary-overlay 自带 的kdic-ec-11w 词典，如果你有自定义的 StarDict 词典，你可以设定自己的词典路径。

存在缺点：目前是通过正则表达式匹配第一个非中文字符串来展示结果。如果第一个非中文字符串是和释义无关的词语，则无法正确显示翻译。
