### ISSUE TITLE
不识别连词符号拼接的词，选择region 也不行

### ISSUE THREAD

**Issue by sawyerzheng** [ginqi7/dictionary-overlay#18]
通过连词符号“-”拼接的词，会被认为是两个词，举例： shake-up， 只会识别出 shake 或者 up，即使手动mark 选择 shake-up也不能添加到生词

**Comment by ginqi7** [comment]
是的，这个是由于现在使用的语句分词工具导致的。现在的分词工具，连接在一起的词会被分割为两个单词。

当前的实现会把整个buffer 进行分词，然后查询每个词语是否在生词本当中，如果在就显示翻译。

即便把 shake-up 加入到了分词本里。分词的时候也会当成两个单词分别处理。

目前可能没有什么好的方法处理这个问题。同理，想要标记词组、短语，目前也是做不到的。
