### ISSUE TITLE
Symbol's function definition is void: file-name-parent-directory

### ISSUE THREAD

**Issue by suliveevil** [ginqi7/dictionary-overlay#19]
https://github.com/ginqi7/dictionary-overlay/blob/72835e759f013e936c166ab39b14fefd4182f7dc/dictionary-overlay.el#L81

请问这个要怎么配置啊？

**Comment by ginqi7** [comment]
你的emacs 是什么版本的？

file-name-parent-directory 应该是 emacs 内部方法吧。怎么会找不到。奇怪。

**Comment by suliveevil** [comment]
emacs-mac 😬

GNU Emacs 28.2 (build 1, aarch64-apple-darwin22.1.0, Carbon Version 169 AppKit 2299)

**Comment by ginqi7** [comment]
describe-function 找不到 file-name-parent-directory 吗？

要是不行，估计考虑使用 file-name-directory 替代。

**Comment by suliveevil** [comment]
找不到。
file-name-directory 能用。

**Comment by qingshuizheng** [comment]
> describe-function 找不到 file-name-parent-directory 吗？
> 
> 要是不行，估计考虑使用 file-name-directory 替代。

我刚才准备了个patch-4 还没提交，把昨天的commit 改成这样：

```
(defcustom dictionary-overlay-user-data-directory
  (expand-file-name "dictionary-overlay-data/" user-emacs-directory)
  "Place user data in Emacs directory."
  :group 'dictionary-overlay
  :type 'string)
```

或者：
```
(defcustom dictionary-overlay-user-data-directory
  (locate-user-emacs-file "dictionary-overlay-data/")
  "Place user data in Emacs directory."
  :group 'dictionary-overlay
  :type 'string)
```
@suliveevil 你把以上这段 eval 一下看行不行？

**Comment by qingshuizheng** [comment]
> 你的emacs 是什么版本的？

想起来昨天 https://github.com/ginqi7/dictionary-overlay/commit/91f78996528601775530d9405f6bd8606de0a7af 引进的`y-or-n-p`是不是29才能用？

**Comment by ginqi7** [comment]
> 想起来昨天 https://github.com/ginqi7/dictionary-overlay/commit/91f78996528601775530d9405f6bd8606de0a7af 引进的y-or-n-p是不是29才能用？

y-or-n-p 早就有了。

file-name-parent-directory 倒是 29 才能用。
使用 describe-function 可以看到方法被引入的版本。

**Comment by suliveevil** [comment]
@qingshuizheng 我现在是这样的：

```emacs-lisp
(defcustom dictionary-overlay-user-data-directory
  (concat (file-name-directory user-init-file)
          "dictionary-overlay-data/")
  "Place user data in Emacs directory.")
```

我是 Emacs 菜鸟，不会编程，代码看得我头疼，只要能跑起来我就不测试了，报歉。

**Comment by qingshuizheng** [comment]
> @qingshuizheng 我现在是这样的：
> 
> ```emacs-lisp
> (defcustom dictionary-overlay-user-data-directory
>   (concat (file-name-directory user-init-file)
>           "dictionary-overlay-data/")
>   "Place user data in Emacs directory.")
> ```
> 
> 我是 Emacs 菜鸟，不会编程，代码看得我头疼，只要能跑起来我就不测试了，报歉。

哈哈我也只是自学了两年，到处抄抄代码，目前勉强能写半个包。
(OT一下: 我们都在BetterAndBetter当群3管理员，鬼盗.噼哩啪)

**Comment by suliveevil** [comment]
好几年前很喜欢 BAB，那时候还有论坛，我写过几个 AppleScript 的帖子，现在貌似关闭了。

以前对 BAB 和 AppleScript 激情过头了，后来就突然反噬，觉得索然无味了。再加上中间有两年没用 Mac，就没怎么关注过 BAB 的近况。虽然现在电脑上还因为情怀装着 BAB，不过从来没用过。

Emacs 应该够我折腾一辈子不挪窝吧，哈哈哈，不过要学的实在是太多了。我仅有的一点编程能力是在用 AppleScript、快捷指令、Alfred、Keyboard Maestro 过程中学到的，太浅薄了……

**Comment by qingshuizheng** [comment]
@ginqi7 

刚发送了个不痛不痒的 PR: https://github.com/ginqi7/dictionary-overlay/pull/20

1. 使用了兼容多数emacs版本的函数：
```
(defcustom dictionary-overlay-user-data-directory
  (locate-user-emacs-file "dictionary-overlay-data/")
  "Place user data in Emacs directory."
  :group 'dictionary-overlay
  :type 'string)
```
2. 修改了大多数行的 fill-column 到 72个字，整体看起来可能改得有点儿多了，要是不喜欢就别合了，嘿嘿

3. 待做的：因为修改了`dictionary-overlay-user-data-directory`， 所以 Readme.org 里有三个关于安装的路径你看看要怎么改，它们都包含`~/.emacs.d/`，一搜就出来了。

**Comment by ginqi7** [comment]
@qingshuizheng 已经合并。大佬的 refine 对我改善代码规范大有益处。

readme 就暂时不改了。~/.emacs.d/ 就作为代表“配置文件目录”的一个参考。

**Comment by qingshuizheng** [comment]
> @qingshuizheng 已经合并。

在折腾中缓缓进步。之前的代码规范也是别人一点一点教我的。

PS：另外在你仓库里好多熟悉的repo，向你学习。
