### ISSUE TITLE
[feature] Add support for "jump_first/last_unknown_word"

### ISSUE THREAD

**Issue by qingshuizheng** [ginqi7/dictionary-overlay#41]
Per title:
Jump to first unknown word and last unknown word. 
I hope I can do it, unfortunately I know nothing about python. /shrug

**Comment by qingshuizheng** [comment]
Also, if the word is last_unknown_word, when press jump next, go to first_unknown_word, 
vice versa, if at first, when press jump prev, go to the last_unknown_word?

**Comment by ginqi7** [comment]
the latest version, it save overlays in an hash table. contains two local-var `dictionary-overlay-hash-table-keys` and `dictionary-overlay-hash-table`

`dictionary-overlay-hash-table-keys` look like:

![image](https://user-images.githubusercontent.com/1028971/204084551-eeb41cc9-d8e7-4a58-9591-d1dc7e5aecb1.png)

it is a string list, reverse order

`dictionary-overlay-hash-table`'s value is an overlay

you could combine `dictionary-overlay-hash-table-keys` and `dictionary-overlay-hash-table` to get first and last overlay.

**Comment by qingshuizheng** [comment]
awesome, gonna give it a try later. thanks. issue closed.

**Comment by ginqi7** [comment]
大佬，你什么时区。怎么感觉随时都能回复。哈哈。

**Comment by qingshuizheng** [comment]
美东，但最近闲着，就变成夜猫了了，其实我现在是早晨6点。一会儿就睡了，你的hash-table大作我来不及研究了哈哈
