### ISSUE TITLE
[提问] 关于文档部分，要写三次么？

### ISSUE THREAD

**Issue by qingshuizheng** [ginqi7/dictionary-overlay#42]
文档包涵了三个地方：
1. defcustom/defvar/defun 本身带doc;
2. .el文件顶端又写了一部分
3. readme.org

第2个是不是可以考虑去掉，写三个地方有点儿累手，修改的时候也容易遗漏。

**Comment by ginqi7** [comment]
>2. el文件顶端又写了一部分

这个当然不是手动写的。在网上找了个 auto-document，写完 elisp 自动运行一下auto-document就好。

https://www.emacswiki.org/emacs/auto-document.el

**Comment by qingshuizheng** [comment]
> 写完 elisp 自动运行一下auto-document就好

哈哈真的是太fancy了。我居然手写，我这手有什么用。（doge
感谢科普，马上安排上。
