### ISSUE TITLE
[feature] add lookup support, allow 3rd dictionary to chime in

### ISSUE THREAD

**Issue by qingshuizheng** [ginqi7/dictionary-overlay#50]
Though dictionary-overlay does a not-bad job in offering quick glance of word meanings, it is still too simple and sometimes provides wrong/off-topic meanings. 

So I think we could allow third dictionaries to chime in, put it in fingertip, especially when you are inside overlay, one tap, and voila, a world of explanations. 

A PR is ready #51 , not perfect, and caveat is, third party dictionary package gets word under cursor in their own way, and doesn't necessarily return the same word as dictionary-overlay gets. Good news is, I haven't met anything deviated too much.

**Comment by ginqi7** [comment]
Thank you for your advice and your efficient action. 

Surprise, there is indeed built-in `dictionary-Lookup-definition`. 

But I can not Look up a word by it, Do I need to install a dictionary?

**Comment by ginqi7** [comment]
I fix a little issue in your code: There needs a quote when assigning a function to a variable.

And try using `dictionary-Lookup-definition` success, It is wonderful.

**Comment by qingshuizheng** [comment]
That is why I’m bring it in. But actually I’m using popweb-dict, 😄

I’m outside again. Will fix it soon.

**Comment by qingshuizheng** [comment]
BTW: _mastering eMacs_ has an introduction to built in dictionary:

https://www.masteringemacs.org/article/wordsmithing-in-emacs

**Comment by ginqi7** [comment]
I already fixed.

https://github.com/ginqi7/dictionary-overlay/commit/c55a8da3294f01524bb143ea6aec7f6bef2d0696

**Comment by qingshuizheng** [comment]
Nice!
