### ISSUE TITLE
Overlay rendering should stay in dedicated buffer

### ISSUE THREAD

**Issue by qingshuizheng** [ginqi7/dictionary-overlay#52]
When there's rendering process ongoing for an extremely long buffer, switching to another buffer would direct the rendering process to the new buffer where the cursor is at.

e.g., I'm rendering buffer on the right side, while waiting for it to finish, i click mouse at the left side, then the rendering focus switches to the left side, thus the messy, blotchy buffer on the left. 

![image](https://user-images.githubusercontent.com/78839107/204730569-1af68e5d-f5ee-4a42-9ac2-fa56b0c9e845.png)

My point is:
1. Are we able to restrict the rendering process to the targeted buffer, without overflowing?
2. When the targeted buffer is killed, the rendering process should stop, otherwise it would rendering everywhere.

Edited:
3. How do I know the rendering process is done, so I can add some hooks to it.

**Comment by ginqi7** [comment]
>Are we able to restrict the rendering process to the targeted buffer, without overflowing? 
When the targeted buffer is killed, the rendering process should stop, otherwise it would rendering everywhere.

Yes, this is a problem. When creating overlays, I don't assign a buffer name. So it will put overlays in the current buffer.

We could send the buffer name to the python program when we run the `refresh-buffer` command, and make-overlay add a specific buffer name.
> 3. How do I know the rendering process is done, so I can add some hooks to it.

This will modify the python code, and let python call your hook when it finishes.

**Comment by ginqi7** [comment]
There is an other problem, the hash-table is also bind with current buffer.

**Comment by qingshuizheng** [comment]
> We could send the buffer name to the python program

Yah, i tried, but to find the source code rooted in python code, so i need some help, now i think you would do it, and take your time. 😉 

> let python call your hook when it finishes

Currently i would love to have a post-rendering hook, either to echo (message "dictionary overlay rendering finished.") or anything special.

> modify the python code

I got to learn some python.

**Comment by ginqi7** [comment]
> Yah, i tried, but to find the source code rooted in python code, so i need some help, now i think you would do it, and take your time. 😉

Implementing this is not hard. but I meet an issue:

I thought using `defvar-local` to define a hash-table, it would create some hash-tables for every buffer automatically. But it won't.

Maybe I should add the buffer name in the hash-table's key?

**Comment by qingshuizheng** [comment]
> add the buffer name in the hash-table's key?

If it works 😸. 

When there's a better way, we then improve it.

**Comment by ginqi7** [comment]
make-overlay bind buffer has been implemented in this commit.

https://github.com/ginqi7/dictionary-overlay/commit/d2a74f66324f5bcee961fada0c549f5880a48589

If you have time, you could review it and do a test.

1. I try setq-local dictionary-overlay-hash-table whenever running 'refresh-buffer';
2. I send a buffer-name to python whenever running 'refresh-buffer';
3. python runs dictionary-add-overlay-from bind a buffer-name  

Btw. I scan my python code with a linter. Too many warnings.

Next, I will fix the warnings

**Comment by qingshuizheng** [comment]
Nice! Wasn't expecting this fast. I'll review in a moment and get back to you.

> tw. I scan my python code with a linter. Too many warnings.

Linters are always to the rescue. Usually I fun flycheck with package-lint, so I can fix while coding.

**Comment by qingshuizheng** [comment]
Oh apologies. Seems hash table is collected, but overlay is not rendering? I need to call `M-x dictionary-overlay-render-buffer RET` again, and overlay will appear immediately.

**Comment by ginqi7** [comment]
I initialize the hash-table on wrong position. I fixed it.

**Comment by qingshuizheng** [comment]
> I initialize the hash-table on wrong position. I fixed it.

 🎉 Works smoothly. Thanks so much.

So now we could proceed to question 2: dictionary-overlay is still rendering after buffer is killed right? I think it does no harm, though it might eat some cpu/mem when a large buffer of text to process?

**Comment by ginqi7** [comment]
There should be no harm. It just runs some simple elisp code(check buffer if it exists)

**Comment by qingshuizheng** [comment]
> There should be no harm. It just runs some simple elisp code(check buffer if it exists)

![image](https://user-images.githubusercontent.com/78839107/204788859-f9992451-48ae-43a2-8a5e-6b4d8bbd2b03.png)

you are right, it stop running when buffer does not exist on every word check.
