### ISSUE TITLE
Lisp error: (void-function string-split)

### ISSUE THREAD

**Issue by bbenchen** [ginqi7/dictionary-overlay#62]
Debugger entered--Lisp error: (void-function string-split)
  string-split("288:300:conceptually:概念上" ":")
  dictionary-overlay-last-unknown-word-pos()
  dictionary-overlay-cursor-after-last-unknown-word-p()
  dictionary-overlay-jump-next-unknown-word()
  #<subr funcall-interactively>(dictionary-overlay-jump-next-unknown-word)
  apply(#<subr funcall-interactively> dictionary-overlay-jump-next-unknown-word)
  funcall-interactively(dictionary-overlay-jump-next-unknown-word)
  #<subr call-interactively>(dictionary-overlay-jump-next-unknown-word nil nil)
  apply(#<subr call-interactively> (dictionary-overlay-jump-next-unknown-word nil nil))
  explain-pause--wrap-call-interactively(#<subr call-interactively> dictionary-overlay-jump-next-unknown-word nil nil)
  apply(explain-pause--wrap-call-interactively #<subr call-interactively> (dictionary-overlay-jump-next-unknown-word nil nil))
  call-interactively(dictionary-overlay-jump-next-unknown-word nil nil)
  command-execute(dictionary-overlay-jump-next-unknown-word)

**Comment by bbenchen** [comment]
emacs的版本是28.2

**Comment by qingshuizheng** [comment]
@cxb811201 
目前我在使用29和30，不确定28.2有没有string-split这个函数(其实它就是split-string的别名)
你C-h f 看一下有没有 split-string 和 string-split?

**Comment by bbenchen** [comment]
定义一个别名就可以，谢谢@qingshuizheng

**Comment by qingshuizheng** [comment]
> 定义一个别名就可以，谢谢@qingshuizheng

我的锅 😆 ，使用了个alias, 这就改回去。等 @ginqi7 有空合上。
感谢捉虫
