### ISSUE TITLE
run dictionary-overlay-lookup  but can not get the result with sdcv

### ISSUE THREAD

**Issue by arstum** [ginqi7/dictionary-overlay#71]
When I run the command "dictionary-overlay-lookup", display the follow messages:
Failed to open server localhost, continue with dict.org?(y or n)

dictionary-check-connection: Failed automatic server selection, please customize dictionary-server

**Comment by ginqi7** [comment]
`dictionary-overlay-lookup` is emacs builtin dictionary.

If you need a english->chinese dictionary, `dictionary-overlay-lookup` maybe not match your goal.

you could use youdao-directory or other user defined dictionaries.
