### ISSUE TITLE
dictionary-overlay-sdcv-dictionary-path路径设置问题

### ISSUE THREAD

**Issue by oxsard** [ginqi7/dictionary-overlay#73]
我用的skywind3000的edict词典，这个比较全比较大。我实在没想到哈利·波特1也有这么多自带词库找不到的单词。。。。

假设/home/jack/a这个目录下包含startdict词典的三个文件。我应该把dictionary-overlay-sdcv-dictionary-path设置为“/home/jack/a”吗，如此设置的话查询单词会报错。难道这是词库的问题？

**Comment by ginqi7** [comment]
路径应该是：/home/jack/a/dictionary-name
并不是目录路径，而是完整的词典路径（不包括文件的后缀名）

**Comment by oxsard** [comment]
> 路径应该是：/home/jack/a/dictionary-name 并不是目录路径，而是完整的词典路径（不包括文件的后缀名）

已经解决，该变量字符串应使用绝对路径，我以前用了相对引用，所以才造成服务器错误。
